djangosite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
urlpatterns = [
	url(r'^', include('shop.urls')),#TemplateView.as_view(template_name='staticpages/index.html'), name='home'),
    url(r'^about/', TemplateView.as_view(template_name='staticpages/about.html'), name='about'),
	#url(r'^shop/', include('shop.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView
from . import views

app_name = 'shop'
urlpatterns = [
	url(r'^$', views.ShopIndexView.as_view()),#TemplateView.as_view(template_name='staticpages/index.html'), name='home'),
    url(r'^shop/(?P<category>[a-zA-Z]*(| [a-zA-Z]*))$', views.ShopView.as_view(), name='shop'),
    url(r'^shop/(?P<pk>[1-9][0-9]*)',views.ProductView.as_view(), name = 'productview'),
    url(r'^about', TemplateView.as_view(template_name='staticpages/about.html'), name='about')
]

shop/models.py
from django.db import models
from django.utils import timezone
import datetime


class Company(models.Model):
	company_name = models.CharField(max_length=100)
	image = models.ImageField(upload_to="shop")
	def __str__(self):
		return self.company_name

class Category(models.Model):
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name

# Create your models here.
class Product(models.Model):
	company = models.ForeignKey(Company, on_delete=models.CASCADE)
	category = models.ManyToManyField(Category)
	description = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	name = models.CharField(max_length=100)
	price = models.DecimalField( max_digits=4, decimal_places=2)
	#image = models.ImageField()
	def __str__(self):
		return self.name

class ProductImage(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	image = models.ImageField(upload_to="shop")

shop/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Product, Category

class ShopView(generic.ListView):
    '''
      Class name: ShopView
      Descritpion: This class is responsible for handing all shop interactions.
    '''
    template_name = 'shop/shop.html'
    context_object_name = 'products'
    model = Product
    order = ["company","description","pub_date","name","price","company__company_name"]
    limit = 4 # number of items on the page bar
    numitems = 6 # number of items to throw on the page
    def pages(self):
      """Returns the maximum possible number of pages."""
      items = Product.objects.all()
      if "category" in self.kwargs:
        items = Product.objects.filter(category__name__contains=self.kwargs["category"])#[start:end]
      else:
        items = Product.objects#[start:end]
      return int(len(items.all())/self.numitems) + 1
    def previous(self):
      page = 1
      if self.request.GET.get("page"):
        page = int(self.request.GET.get("page"))
      if page != None and page > 1:
          page -= 1
      return page
    def current(self):
      page = 1
      if self.request.GET.get("page"):
        print ("PAGE")
        print (page)
        page = int(self.request.GET.get("page"))
      return page
    def next(self):
      page = 1
      if self.request.GET.get("page"):
        page = int(self.request.GET.get("page"))
      if page != None and page < self.pages():
          page += 1
      return page
    def first(self):
      return 1
    def last(self):
      return self.pages()
    def pagination(self):
      numpages = self.pages()
      page = 1

      if self.request.GET.get("page"):
          page = int(self.request.GET.get("page"))

      page = page - 1

      page = page - page % self.limit

      if page  <= 0:
        page = 1
      end = page + self.limit-1 if page + self.limit-1 <= numpages else numpages

      outlist = range(page,end+1)

      return range(page,end+1)
    def get_queryset(self):
        """Change me"""

        order_by = "pub_date"

        start = 0
        end = self.numitems

        # www.google.com/something/blah/?order_by=whatever
        if self.request.GET.get("order_by"):
        	order_by = (self.request.GET.get("order_by"))

        	if not order_by in self.order:
        		order_by = "pub_date"
       	if self.request.GET.get("page"):
       		page = int(self.request.GET.get("page"))
       		start = (page-1)*self.numitems
       		end = self.numitems * page
      	# urls view can be used for args and kwargs...
        #print (self.username)
        print (self.kwargs)
        if "category" in self.kwargs:
          return Product.objects.order_by(order_by).filter(category__name__contains=self.kwargs["category"])[start:end]
        else:
          return Product.objects.order_by(order_by)[start:end] #filter(pub_date__lte=timezone.now())

    # Not necessary
    def get_context_data(self, **kwargs):
        context = super(ShopView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

class ProductView(generic.DetailView):
  context_object_name = "product"
  template_name = 'shop/productdetail.html'
  def get_queryset(self):
    #print self.args
    return Product.objects

'''def get_product(request,product_id):
  product = get_object_or_404(Product, pk=product_id)
  try:
    selected_product = product.choice_set.get(pk=request.POST['choice'])
  except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
  else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('shop:product_listing', args=(product.id,)))'''
class ShopIndexView(ShopView):
  context_object_name = "product"
  template_name = 'shop/index.html'

  def firstitem(self):
    order_by = "pub_date"
    return Product.objects.order_by(order_by)[0]
  def carousel(self):
    order_by = "pub_date"
    return Product.objects.order_by(order_by)[1:5]
    
  def get_queryset(self):
    return Product.objects

  def nextten(self):
    #print (len(Product.objects.order_by("pub_date")[5:16]))
    return Product.objects.order_by("pub_date")[5:16]

shop/templates/shop/index.html
{% extends "staticpages/index.html" %}

{% block main %}

<style>
.carousel-inner > .item > img,
.carousel-inner > .item > a > img {
	margin: auto;
	width: auto;
  	height: 225px;
  	max-height: 225px;
}



.left.carousel-control, .right.carousel-control
{
	margin: auto;
	background-color:transparent;
}

.products-index
{
	column-count: 2;
	column-gap: 200px;
	column-width: 400px;
	margin-left:auto;
    margin-right:auto;
    width:1200px;
}
.carouseltext
{
	position: absolute;
	top: 90%; 
   left: 90%; 
   	margin-left:auto;
    margin-right:auto;
   color: white;
   background-color: black;
}


</style>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  	<div class="item active">
  			{% with view.firstitem.productimage_set.all|first as image %}
  			<a href="{%url 'shop:productview' image.id %}">
      		<img src="{{ image.image.url }}" alt="{{view.firstitem.name}}" height="400" width="400">
      		</a>
      		<span class="carouseltext"> ${{view.firstitem.price}} </span>
      		{% endwith %}
   	</div>
  	{% for i in view.carousel %}
  	    <div class="item">
  	    	{% with i.productimage_set.all|first as image %}
  	    	<a href="{%url 'shop:productview' i.id %}">
      		<img src="{{ image.image.url }}" alt="{{i.name}}" width="400" height="400" >
      		</a>
      		<span class="carouseltext"> ${{i.price}} </span>
      		{% endwith %}
    	</div>
  	{% endfor %}
    <!--<div class="item active">
      <img src="img_chania.jpg" alt="Chania">
    </div>

    <div class="item">
      <img src="img_chania2.jpg" alt="Chania">
    </div>

    <div class="item">
      <img src="img_flower.jpg" alt="Flower">
    </div>

    <div class="item">
      <img src="img_flower2.jpg" alt="Flower">
    </div>-->
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<nav class="product-filter">
<div id="shopcontent" class="products-index">
{% if view.nextten %}

    {% for product in view.nextten %}

    <div class="product">
        <!-- Just grabing the first product here  -->
    	{% with product.productimage_set.all|first as image %}
        <a href="{%url 'shop:productview' product.id %}"><img src="{{ image.image.url }}" width="400" height="400"> </a>
        {% endwith %}
        <h5>{{product.name}}</h5>
        <h6>{{product.description}}</h6>
        <h6>{{product.price}}$</h6>
        <button type="button">Add to Cart</button> 
    </div>
    <div class="product">
    	<a href=""><img  src="" width="400" height="400"> </a>
    	<h5> name </h5>
    	<h6> description </h6>
    	<h6> price </h6>
    	<button type="button">Add to Cart</button> 

	</div>

    {% endfor %}

{% else %}
    <p>No content on this page.</p>
{% endif %}

</div>
</nav>

{% endblock %}

shop/templates/shop/productdetail.html
{% extends "staticpages/index.html" %}

{% block main %}

{{product.name}}
{{product.price}}
{{product.description}}

{% endblock %}

shop/templates/shop/shop.html
{% extends "staticpages/index.html" %}
{% load shop_extras %}

{% block main %}
{% load staticfiles %}


<!--
<div id="mytestid">
apples are amazing... {{ view.pages }}
</div>
-->
{% if categories %}
    <select>
    {% for category in categories %}
        <option value="{{category}}"> {{category}}</option>
    {% endfor %}
    </select>
{% endif %}
<nav class="product-filter">
<div id="shopcontent" class="products">
{% if products %}

    {% for product in products %}
    <div class="product">
        <!-- Just grabing the first product here  -->
    	{% with product.productimage_set.all|first as image %}
        <a href="{%url 'shop:productview' product.id %}"><img src="{{ image.image.url }}" width="400" height="400"/> </a>
        {% endwith %}
        <h5>{{product.name}}</h5>
        <h6>{{product.description}}</h6>
        <h6>{{product.price}}$</h6>
        <button type="button">Add to Cart</button> 
    </div>
    {% endfor %}

{% else %}
    <p>No content on this page.</p>
{% endif %}

</div>
</nav>

<div class="pagination">

{% if view.current != 1%}
<a class="pagelink" href="?page={{ view.previous }}">&#10094; </a>
{% else %}
<a class="pagelink-disabled" >&#10094; </a>
{% endif %}

{% if not view.first in view.pagination %}
<a class="pagelink" href="?page={{view.first}}">{{view.first}} </a>
<a class="pagelink-disabled" >... </a>
{% endif %}

{% for i in view.pagination %}
{%if i != view.current %}
<a href="?page={{i}}" class="pagelink" >{{i}} </a>
{% else %}
<a class="pagelink-disabled" >{{i}} </a> 
{% endif %}
{% endfor %}

{% if view.last in view.pagination %}

{% else %}
<a class="pagelink-disabled" >... </a>
<a class="pagelink" href="?page={{view.last}}">{{view.last}} </a>
{% endif %}

{% if view.current != view.pages%}
<a class="pagelink" href="?page={{view.next}}">&#10095; </a>
{% else %}
<a class="pagelink-disabled" >&#10095; </a>
{% endif %}



</div>
{% endblock %}

shop/templates/staticpages/about.html
{% extends "staticpages/index.html" %}

            {% block main %} About {% endblock %}

shop/templates/staticpages/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static "css/shop.css" %}" />
        <link rel="stylesheet" type="text/css" href = '{% static "style/style.css" %}'>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        



    </head>
    <body>
             <ul class="mainbar">
                <li class="bartext"><a href="/about/">About Us</a></li>
                <li class="dropdown"><a href="/shop/" class="dropbtn" >Product</a>
                <!-- onclick= "drpdwn()" -->   
                <div class="dropdown-content" >
                        <a href="/shop/RPG">RPG</a>
                        <a href="/shop/Board Game">Board Game</a>
                        <a href="/shop/Fantasy">Fantasy</a>
                        <a href="/shop/Strategy">Strategy</a>
                        <a href="/shop/Action">Action</a>
                        <a href="/shop/Adventure">Adventure</a>
                        <a href="/shop/Casual">Casual</a>
                        <a href="/shop/Indie">Indie</a>
                        <a href="/shop/Racing">Racing</a>
                        <a href="/shop/Simulation">Simulation</a>
                        <a href="/shop/Sports">Sports</a>
                        <a href="/shop/Massively Multiplayer">Massively Multiplayer</a>
                    </div> 
                </li> 
                <li class="bartext"><a href="/">Home</a></li>
                <li class="logo"><a href="/"><img src= "{% static 'images/logo.png' %}" alt="logo" height = "20"/></a></li>
            </ul>

        <main>
            {% block main %} Home {% endblock %}
        </main>
    </body>
</html>

shop/templates/staticpages/sales.html
<html>
    <head>
        <link rel = "stylesheet" type = "text/css" href = "style/style.css">
    </head>
    <body>
        <nav>
             <ul>
                <li><a href="about.html">About Us</a></li>
                <li><a href="javascript:void(0)" class = "dropbtn" onclick= "drpdwn()">Product</a>
                    <div class = "dropdown-content" id = "myDropdown">
                        <a href="sales.html">Link 1</a>
                        <a href="#">Link 2</a>
                        <a href="#">Link 3</a>
                    </div>
                    </li>
                <li><a href="index.html">Home</a></li>
                <li class="logo"><a href="index.html"><img src= "images/logo.png" alt="logo" height = "20"/></a></li>
            </ul>
            <script>
                function drpdwn(){
                    document.getElementById("myDropdown").classList.toggle("show");
                }
                
                window.onclick = function(e){
                    if (!e.target.matches('.dropbtn')){
                        var dropdowns = document.getElementsByClassName("dropdown-content");
                        for (var d = 0; d < dropdowns.length; d++){
                            var openDropdown = dropdowns[d];
                            if(openDropdown.classList.contains('show')){
                                openDropdown.classList.remove('show');
                            }
                        }
                    }
                }
            </script>
        </nav>
        <main>
            Products
        </main>
    </body>
</html>